trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

parameters:
  hugo_version: '0.60.1'

steps:
- checkout: self
  persistCredentials: true
  clean: true
  displayName: 'Checkout'

- script: |
    git config --global user.email "rainer@software-architects.at"
    git config --global user.name "Rainer"
  displayName: 'Git Settings'

- script: |
    wget https://github.com/gohugoio/hugo/releases/download/v${{ parameters.hugo_version }}/hugo_${{ parameters.hugo_version }}_Linux-64bit.deb \
        -O '$(Pipeline.Workspace)/hugo_${{ parameters.hugo_version }}_Linux-64bit.deb'
    sudo dpkg -i $(Pipeline.Workspace)/hugo*.deb
  displayName: 'Install Hugo'

- script: |
    hugo
  displayName: 'Build'

- task: CopyFiles@2
  inputs:
    sourceFolder: public
    targetFolder: $(Agent.TempDirectory)/public
    cleanTargetFolder: true
    overWrite: true
  displayName: 'Copy build result to temp'

- script: |
    git checkout gh-pages
  displayName: 'Switch to gh-pages branch'

- task: CopyFiles@2
  inputs:
    sourceFolder: $(Agent.TempDirectory)/public
    targetFolder: .
    overWrite: true
  displayName: 'Copy build results to gh-pages branch'

- script: |
    git add --all .
    git commit -m 'Update website'
    git push origin gh-pages
  displayName: 'Git push gh-pages branch'
