trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  clean: true
  displayName: 'Checkout'

- script: |
    git config --global user.email "rainer@software-architects.at"
    git config --global user.name "Rainer"
  displayName: 'Git Settings'

- script: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
    test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
    test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
    test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
    echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
  displayName: 'Install Linuxbrew'

- script: |
    brew install hugo
  displayName: 'Install Hugo'

- script: |
    hugo
  displayName: 'Build'

- task: CopyFiles@2
  inputs:
    sourceFolder: public
    targetFolder: $(Agent.TempDirectory)/public
    cleanTargetFolder: true
    overWrite: true
  displayName: 'Copy build result to temp'

- script: |
    git checkout gh-pages
  displayName: 'Switch to gh-pages branch'

- task: CopyFiles@2
  inputs:
    sourceFolder: $(Agent.TempDirectory)/public
    targetFolder: .
    overWrite: true
  displayName: 'Copy build results to gh-pages branch'

- script: |
    git add --all .
    git commit -m 'Update website'
    git push origin gh-pages
  displayName: 'Git push gh-pages branch'
